### ISSUE TITLE
DDD Melbourne Workshop - The Zen of Git

### ISSUE THREAD

**Issue by shiftkey** [shiftkey/talks#9]
Duration: 45mins

Here's the summary:

> If you're familiar with Git and want to dig deeper, this is the workshop for you. We'll learn a bit about some advanced Git commands, as well as cover workflows for collaborating with others and perhaps some Git internals if time permits.
> 
> You should bring a laptop with Git installed, so you can follow along. Have some local repositories to experiment with, as we may not have WiFi at the venue.
> 
> *Note: you can totally corner me at the after-party if you have specific Git questions you’d like to corner me about. Just as long as we talk about it over a beer.*

I could go off about *a lot* here, but I only have so much time. Thoughts?

**Comment by kpfaulkner** [comment]
Guessing workshops aren't recorded?

**Comment by shiftkey** [comment]
@kpfaulkner I don't believe so /ping @pjimmy

I'd love to get some content in here for those who can't make it, not sure of the format I'll run this bit in.

**Comment by jk** [comment]
I suggest covering interactive rebasing, rewriting history (remove committed passwords etc.) and git bisect.

Are you aware of [GitHubs training material](https://training.github.com)?

**Comment by jimmyp** [comment]
No sorry, I don't think workshops will be recorded. We only have resources to record a small part of the content and the workshops interactive natures make them difficult to do well.

**Comment by shiftkey** [comment]
Some topics I've covered in the past:

 - Good Git Habits - small, focused commits, branch early and often, etc
 - Git At Scale - popular branching models and choosing the right one for your team 
 - The Eternal Merge vs Rebase War - when to do each, the pros and cons
 - The Immutability Of Git - understanding `cherry-pick` and thus `rebase`
 - The Mutability Of Git - `reset`, amending commits, rewriting history, and also `rebase` goes here lol
 - Git Internals - "it's just a filesystem!"

I might just gather up a bunch of topics, gauge audience interest on the day (they'll have topics that interest them, or perhaps unexpected ones) and go from there...

@jk I might get to bisect but it's not something I use often, so I probably won't do it justice.
